### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by robrwg** [acts-project/covfie#24]
Went to https://covfie.readthedocs.io/en/latest/ and got 404

**Comment by stephenswat** [comment]
Hi @robrwg, thanks for the message. It appears this broke as we moved this repository to the official ACTS project. Perhaps @paulgessinger, who I believe is in charge of the ACTS documentation, can help with the ACTS RTD project?

**Comment by stephenswat** [comment]
Paul has fixed the documentation which is now available on https://covfie.readthedocs.io/ once more. Thank for you for the issue report! :slightly_smiling_face:
